wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1671812839
    t:
      1:
      - 5
      - 53
      - 55
      - 80
      2:
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 16
      4: 3.10.8
      5: 0.12.21
      8:
      - 3
      - 5
      - 9
bbox_col:
  desc: null
  value: null
caption_col:
  desc: null
  value: TEXT
compute_hash:
  desc: null
  value: sha256
disable_all_reencoding:
  desc: null
  value: false
disallowed_header_directives:
  desc: null
  value:
  - noai
  - noimageai
  - noindex
  - noimageindex
distributor:
  desc: null
  value: multiprocessing
downloader:
  desc: null
  value: normal
downscale_interpolation:
  desc: null
  value: area
enable_wandb:
  desc: null
  value: true
encode_format:
  desc: null
  value: jpg
encode_quality:
  desc: null
  value: 95
extract_exif:
  desc: null
  value: true
image_size:
  desc: null
  value: 256
incremental_mode:
  desc: null
  value: incremental
input_format:
  desc: null
  value: parquet
max_aspect_ratio:
  desc: null
  value: .inf
max_image_area:
  desc: null
  value: .inf
max_shard_retry:
  desc: null
  value: 1
min_image_size:
  desc: null
  value: 0
number_sample_per_shard:
  desc: null
  value: 1000
oom_shard_count:
  desc: null
  value: 5
output_folder:
  desc: null
  value: F:\FYP\datasets
output_format:
  desc: null
  value: webdataset
processes_count:
  desc: null
  value: 16
resize_mode:
  desc: null
  value: border
resize_only_if_bigger:
  desc: null
  value: false
retries:
  desc: null
  value: 0
save_additional_columns:
  desc: null
  value: null
skip_reencode:
  desc: null
  value: false
subjob_size:
  desc: null
  value: 1000
thread_count:
  desc: null
  value: 32
timeout:
  desc: null
  value: 10
upscale_interpolation:
  desc: null
  value: lanczos
url_col:
  desc: null
  value: URL
url_list:
  desc: null
  value: mscoco.parquet
user_agent_token:
  desc: null
  value: null
wandb_project:
  desc: null
  value: img2dataset
